### ISSUE TITLE
error creating apos-app (apos create apos-app)

### ISSUE THREAD

**Issue by lumos94** [apostrophecms/apostrophe-cli#49]
Running `apos create apos-app` throws this error:
```
Apostrophe  Unable to locate an app.js in this directory. You need to be in the root directory of an Apostrophe project to run this command.  Failed
(node:17960) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

Running `apos create-project apos-app` throws this error: 

```
 Apostrophe  create-project  Grabbing the boilerplate from Github [1/2]
Cloning into 'apos-app'...

 Apostrophe  create-project  Setting up your project shortname [2/2]
(node:13660) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

![image](https://user-images.githubusercontent.com/24844718/126117669-1810fa98-86a2-45c5-aa5e-a109087b564d.png)

**Comment by abea** [comment]
`apos create` is not a command in this version of the CLI tool. This version falls back to trying to run an Apostrophe app task if the command isn't one of the ones built into the tool. That's why it's trying to find the app.js file.

In the process of getting to that error it creates the `apos-app` directory, so when you ran the second, correct command it should fail because the directory already exits. I'm not sure about the padLevels error. Maybe that's an older version or a Windows-specific warning? I'm not seeing it with the  current version of this.

All that said, it looks like you're trying to use the new CLI, which _does_ use `apos create`. That's `@apostrophecms/cli` (we're moving to a namespace). I'm going to PR this repo with a deprecation message.

**Comment by lumos94** [comment]
I have been following the documentation when I got the error, So maybe that needs update as well!
https://v3.docs.apostrophecms.org/guide/setting-up.html#creating-a-project

**Comment by abea** [comment]
Sure, but did you install `npm install @apostrophecms/cli` or `apostrophecms-cli`? The second one will result in this bug. The first one should not.

This issue is on the older, deprecated CLI version that would produce this issue.

**Comment by lumos94** [comment]
I have installed `npm install @apostrophecms/cli` as per the documentation! I followed the steps in the documentation mentioned above step by step! That's why I was surprised when I got the error!

**Comment by abea** [comment]
You may already have the older one installed. The output in your screenshot is the older CLI tool. `create-project` isn't a label in the new one and the colors are different.
